### ISSUE TITLE
Query2 TODO for 0.8

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/activitywatch#159]
**Beta 1:**
- [x] Add appnames for firefox and chrome on:
  - [x] Linux
  - [x] Windows
  - [x] macOS
- [x] Revert unfinished aw-client heartbeat caching

**Beta 2:**

- [x] Make it possible for query requests to return multiple datasets?
- [x] ~~Move aw_transform from aw_core to aw_analysis?~~
- [x] Expose get_eventcount as a query function
- [x] Expose get_eventcount over REST API

**Before release:**
- [x] Discuss the names of all query functions so we won't have to change them later and deprecate old names
- [ ] Finish docs

**Comment by johan-bjareholt** [comment]
Reopening this, need to not forget the "before release" tasks before we do the next release.

**Comment by ErikBjare** [comment]
@johan-bjareholt Isn't this practically done? We have some docs at https://activitywatch.readthedocs.io/en/latest/api-reference.html#aw-transform which are not perfect but might be good enough for this issue to be closed.

**Comment by johan-bjareholt** [comment]
I think that we should close this issue and create a new one for more ambitious plan for proper documentation of query2

**Comment by xylix** [comment]
@johan-bjareholt Did anyone ever create a new issue for the more ambitious documentation plan?

**Comment by johan-bjareholt** [comment]
@xylix Not yet

**Comment by xylix** [comment]
Could you insert details at #372 (what other things need to be documented, set priority and size labels correctly)?
