### ISSUE TITLE
Switching to GitHub Actions

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#388]
So I've been playing with this in #382, and I'm impressed.

Motivations:

 - Better build times (especially for macOS and Windows), see #370.
 - Integrated into GitHub, better UX in general
 - Easier/cleaner config (especially with regards to multi-platform support)
 - Seems more reliable
   - Not a high bar to beat
   - Travis has had outages, build backlogs, builds stalling
   - I've been getting "An error occurred while generating the build script." frequently recently (the last two days) for macOS builds.
 - It makes us able to finally get rid of Appveyor and unify our CI process
 - It allows for more advanced automation, such as automating creating releases with changelog and everything.

I'm seriously tired of mucking with Travis and Appveyor, especially due to the long build times, so pretty excited about getting this done, so we can scrap them.

### Subtasks before ready to completely migrate to GitHub Actions:

 - [x] Upload build artifacts on every build
 - [x] Upload releases to GitHub releases
     - Can even automate the creating of the release, including generating the release description & changelog. See: https://github.com/actions/upload-release-asset
 - [x] Add caching for `aw-server-rust/target`
 - [x] Build aw-server-rust in debug mode on non-releases (for faster builds), see https://github.com/ActivityWatch/aw-server-rust/pull/100
 - [x] Test builds on all platforms
    - [x] Linux
      - ~~Problems found, see comments.~~
      - Fixed in #604
    - [x] Windows
    - [x] macOS (done in https://github.com/ActivityWatch/activitywatch/issues/388#issuecomment-751726505)
      - [x] Problems anticipated on versions of macOS older than the version used in CI, probably need to do some xcode-select magic (done in https://github.com/ActivityWatch/activitywatch/pull/544/commits/9f0f7c7af389cd878889b60e9c9b00c1bb878d7f)
          - [x] Stumbled into some issues... Might work now, but should check with otool to be sure: https://stackoverflow.com/questions/17143373/determine-minimum-osx-version-a-binary-was-compiled-for (done in https://github.com/ActivityWatch/activitywatch/pull/544#issuecomment-751801675)

### Progress on moving module repos to GitHub Actions:

 - [x] aw-server (https://github.com/ActivityWatch/aw-server/pull/73)
 - [x] aw-server-rust
 - [x] aw-webui
 - [x] aw-qt (https://github.com/ActivityWatch/aw-qt/commit/20261da3f38731f30726b15531943bc9e5332de1)
 - [x] aw-core (https://github.com/ActivityWatch/aw-core/pull/89)
 - [x] aw-client (https://github.com/ActivityWatch/aw-client/pull/51)
 - [x] aw-watcher-afk (https://github.com/ActivityWatch/aw-watcher-afk/commit/4b9eea5e1bd71e90f07bee159ae17ab03615a8c9)
 - [x] aw-watcher-web (https://github.com/ActivityWatch/aw-watcher-web/pull/63)
 - [x] aw-watcher-window
 - [x] activitywatch.github.io (https://github.com/ActivityWatch/activitywatch.github.io/issues/13) 

### An overview of migration progress can also be seen on the [CI overview page](https://activitywatch.net/ci/)

**Comment by ErikBjare** [comment]
Testing the Linux build gives me SIGSEGV as soon as I right-click the tray icon:

```
(lots of similar lines above)
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
Fontconfig warning: FcPattern object weight does not accept value [40 210)
fish: “./aw-qt --testing --autostart-m…” terminated by signal SIGSEGV (Address boundary error)
```

Testing a recent version from Travis gives me similar Fontconfig error/warnings (and super ugly font in the tray icon menu), but doesn't SIGSEGV.

**Comment by xylix** [comment]
Did you try rebuilding the qt reaources after changing pyqt version?

**Comment by ErikBjare** [comment]
@xylix They are built in CI, nothing to rebuild.

**Comment by johan-bjareholt** [comment]
A bit of a shame to get even more locked into the GitHub ecosystem, but considering how much of an improvement it seems to be and the time spent it seems to definitely be worth it.

**Comment by ErikBjare** [comment]
>A bit of a shame to get even more locked into the GitHub ecosystem

I agree, but to be fair GitHub has been doing a lot of things right recently (apart from closing repos because of US embargoes, but their hands are tied) and at this point they *are* the ecosystem (with the acquisition of npm, semmle, dependabot, etc).

**Comment by johan-bjareholt** [comment]
> at this point they are the ecosystem

Disagree, but that's off topic I guess.

**Comment by ErikBjare** [comment]
As @xylix mentioned on Discord, Travis will start charging for macOS instances, so we'll have to migrate at least the macOS builds pretty soon.

**Comment by ErikBjare** [comment]
Just tested the latest GitHub Actions macOS build (from master), works fine.

**Comment by ErikBjare** [comment]
Found a couple of hints for the SIGSEGV on Linux:

 - https://github.com/pyinstaller/pyinstaller/issues/4985
 - https://github.com/pyinstaller/pyinstaller/issues/4970

I can for example run this without issue, although no trayicon appears:

```
env QT_QPA_PLATFORM=minimal QT_DEBUG_PLUGINS=1 LD_PRELOAD=/usr/lib64/libfreetype.so:/usr/lib64/libfontconfig.so ./aw-qt --autostart-modules 'none'
```

But this fails:

```
env QT_QPA_PLATFORM=xcb QT_DEBUG_PLUGINS=1 LD_PRELOAD=/usr/lib64/libfreetype.so:/usr/lib64/libfontconfig.so ./aw-qt --autostart-modules 'none'
```

With the output (truncated):

```
...
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/erb/Applications/ActivityWatch/activitywatch/platforms" ...
loaded library "/home/erb/Applications/ActivityWatch/activitywatch/PyQt5/Qt/plugins/platforms/libqxcb.so"
loaded library "Xcursor"
fish: Job 1, 'env QT_QPA_PLATFORM=xcb  QT_DEB…' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by ErikBjare** [comment]
#604 worked! 

Looks like we are good to go! (assuming the Windows build is fine)

**Comment by ErikBjare** [comment]
This was completed a while back. Nice to finally be done with it.
