### ISSUE TITLE
Release checklist for version 0.7

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#47]
Checklist moved here from: https://github.com/ActivityWatch/activitywatch/pull/34

This is planned to be the last in the `0.x` series, will be followed by `1.0` if all goes according to plan.

- [x] Update submodules
  - [x] Merge current set of stable improvements
    - [x] https://github.com/ActivityWatch/aw-client/pull/12
    - [x] https://github.com/ActivityWatch/aw-core/pull/23
- [x] Packaging
  - [x] Unify build/install/CI scripts using makefile (see #43)
  - [x] Fix macOS packaging (see https://github.com/ActivityWatch/activitywatch/issues/27)
  - [x] ~~Create Debian package~~
- [x] Passing builds in CI
  - [x] Travis
  - [x] Run all tests in submodules (~~use pytest for test discovery~~, call their `make test`)
  - [x] AppVeyor ~~(might be delayed to a later version)~~
     - [x] Upload artifact on releases

**Comment by ErikBjare** [comment]
So, basically all that's left is making Appveyor upload the build upon release.

**Comment by ErikBjare** [comment]
Appveyor now creates the artifact properly, deployment to GitHub releases needs to be done manually however (should be possible to automate but Appveyor docs were unclear).

I'll try to get proper Windows support in as well, see issue #28.

**Comment by ErikBjare** [comment]
Closing this in favor of the final blocker for v0.7: #69
