### ISSUE TITLE
v0.10.0 release checklist

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#490]
- [x] Essential builds passing
 - [x] Fix issues in aw-qt
   - Fixed in https://github.com/ActivityWatch/aw-qt/commit/83cc4db2d48d715d6b708eb6b061bccd6ec6c079
 - [x] Update version in Cargo.toml
 - [x] Fix/move remaining issues in https://github.com/ActivityWatch/activitywatch/milestone/5
 - [x] Test builds
   - [x] on Linux
   - [x] on Windows
      - I didn't really, I'm just assuming...
      - Update: I tested the release now, works great!
   - [x] on macOS
 - [x] Write release notes
   - Improvements to changelog generation in https://github.com/ActivityWatch/activitywatch/pull/505
   - Thank @xylix for his work on macOS support and improvements to aw-qt
   - Thank @billangli for his work on the update check
   - Thank FUUG.fi for their €3k grant, and write the grant report (https://github.com/ActivityWatch/activitywatch/issues/514)

## After release

 - [x] Publicize the release as described in #38 
    - [x] Twitter
    - [x] Facebook (automated from the Tweet by Zapier)
    - [x] Discord
    - [x] reddit
      - https://www.reddit.com/r/Python/comments/k0405d/new_major_version_release_of_activitywatch_the/
      - https://www.reddit.com/r/coolgithubprojects/comments/k0427v/activitywatch_the_probably_best_opensource/
 - [x] Update https://github.com/ActivityWatch/aur-activitywatch-bin
 - [x] ~~Finally complete the drafted Development Update on the forum~~
 - [x] Write report for FUUG.fi grant (#514)

**Comment by ErikBjare** [comment]
![image](https://user-images.githubusercontent.com/1405370/95017831-ed6bfd00-065b-11eb-95b8-8a6515b5e458.png)

Update check looking good, thanks @billangli!

@johan-bjareholt We need to start setting a proper version for aw-server-rust.

**Comment by johan-bjareholt** [comment]
I'd say we name this 0.10.0 instead.
There are new features so there's no reason to not increase the minor version.
Also, just update the version in aw-server/Cargo.toml in aw-server-rust to update its version.
